name: workflow
on:
  push:
env:
   GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - run: { echo '${{ toJSON(github.event.ref) }}'; echo '${{ toJSON(github.event.repository) }}'; } > file.txt
    - run: |
         git add .
         git commit -m "added files"
         git push -fu origin main
    
