name: workflow
on:
  push:
env:
   GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - run: | 
       git clone --branch main https://centralpavangit:$GIT_TOKEN@github.com/centralpavangit/hello-world-docker-action.git code
       cd code
       git config --global user.name "centralpavangit"
       git config --global user.email "mr.pavand@gmail.com"
       curl -u "centralpavangit:$GIT_TOKEN" https://github.com/centralpavanigit/hello-world-docker-action.git
       { echo '${{ toJSON(github.event.ref) }}'; echo '${{ toJSON(github.event.repository) }}'; } > file.txt
       git add .
       git commit -m "added"
       git push -f
