name: workflow
on:
  push:
env:
   GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - run: echo "$(echo '${{ github.event.ref }}')\n$(echo '${{ github.event.repository.clone_url }}')" > file.txt
    - run: |
         git add .
         git config --global user.name "centralpavangit"
         git config --global user.email "mr.pavand@gmail.com"
         git commit -m "added files"
         git push -fu origin main
    
