name: workflow
on:
  push:
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - run: | 
       { echo '${{ toJSON(github.event.ref) }}'; echo '${{ toJSON(github.event.repository) }}'; } > file.txt
       git init
       git config --global user.name "centralpavangit"
       git config --global user.email "mr.pavand@gmail.com"
       git add .
       git commit -m "added"
       git push -f
