name: workflow
on:
  push:
jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
    - run: | 
       { echo '${{ toJSON(github.event.ref) }}' ; echo '${{ toJSON(github.event.repository) }}'; } > file.txt
